version: '3.1'
services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./headersOutput.js:/etc/nginx/headersOutput.js
    ports:
      - 8080:80
    extra_hosts:
      - host.docker.internal:host-gateway

  target-service:
    image: mendhak/http-https-echo
    ports:
      - 8081:8080
    extra_hosts:
      - host.docker.internal:host-gateway
