name: PR Prerelase

env:
  NUGET_OUTPUT: ./Artifacts/NuGet
  NUGET_SOURCE: https://nuget.pkg.github.com/aksio-insurtech/index.json
  DOTNET_VERSION: "6.0.400"
  INGRESS_MIDDLEWARE_CACHE: "ingress-middleware-cache-${{ github.sha }}"

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - "**"
    paths:
      - "Source/**"
      - ".github/workflows/**"

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.release.outputs.version }}
      publish: ${{ steps.release.outputs.should-publish }}
      prerelease: ${{ steps.release.outputs.prerelease }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Release
        id: release
        uses: aksio-insurtech/release-action@v1
        with:
          user-name: "Aksio Build"
          user-email: "build@aksio.no"

  ingress-middleware:
    if: needs.release.outputs.publish == 'true'
    runs-on: ubuntu-latest
    needs: [release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - uses: actions/cache@v3
        id: ingress-middleware-output
        with:
          path: ./Source/out
          key: ${{ env.INGRESS_MIDDLEWARE_CACHE }}

      - name: Build
        working-directory: ./Source
        run: |
          dotnet publish -c Debug -o out/x64
          cp -r out/x64 out/arm64

  publish-docker:
    if: needs.release.outputs.publish == 'true'
    runs-on: ubuntu-latest
    needs: [ingress-middleware, release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: ingress-middleware-output
        with:
          path: ./Source/out
          key: ${{ env.INGRESS_MIDDLEWARE_CACHE }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Development Docker Image
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Docker/Development/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/aksio-insurtech/ingressmiddleware:${{ needs.release.outputs.version }}
          build-args: |
            VERSION=${{ needs.release.outputs.version }}
            ENTRYPOINT=pr_entrypoint.sh

      - name: Add comment for Docker image
        uses: mshick/add-pr-comment@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message: |
            Docker Image for this PR:
            https://ghcr.io/aksio-insurtech/ingressmiddleware:${{ needs.release.outputs.version }}

            docker run ghcr.io/aksio-insurtech/ingressmiddleware:${{ needs.release.outputs.version }}
          allow-repeats: false
